### PR TITLE
Add React-Admin frontend & Improve dev container

### PR DESCRIPTION
**Pull request by BigCheeze45**
This PR is a bit big but adds the remaining components needed for the VMS:

- [Django REST framework](https://www.django-rest-framework.org) - set this up following tutorial in the docs.
- [React-Admin frontend](https://marmelab.com/react-admin/) - similarly, set this up following tutorial in the docs.
- Miscellaneous improvements to dev container setup

### CODE REVIEW

**Review by waverlymomo — APPROVED** [review]

**Review by rodcaballero — APPROVED** [review]
Awesome

**Review by rstoyano — APPROVED** [review]
I approved

**Review by tstoyano — COMMENTED** [review]
Thank you.

**Review by tstoyano — COMMENTED** [review]
Great!

**Comment by tstoyano** [comment]
Reviewd

**Pull request merged**
