### PR TITLE
Add devcontainer for easy development

### PR DESCRIPTION
**Pull request by BigCheeze45**
This change adds [dev containers](https://containers.dev) to simplify and streamline developers. This includes all the tools and dependencies and provides a standardized environment. With this, you can work on the codebase without having to install anything other than docker & git.

Additionally, this add [pre-commit hooks](https://pre-commit.com/#advanced) to perform linting and formatting checks prior to committing.

### CODE REVIEW

**Review by rodcaballero — COMMENTED** [review]
Great Work!!

**Comment by tstoyano** [comment]
Thank you Prince

**Review by tstoyano — COMMENTED** [review]
Thank you Prince

**Review by rstoyano — COMMENTED** [review]
Amazing!

**Review by tstoyano — COMMENTED** [review]
Thank you!

**Pull request merged**
